before_script:
  - python --version
  - ansible --version
  - mkdir tests/roles
  - ln -s $(pwd) tests/roles/diamond
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=./tests/roles' > ansible.cfg

# required for `ansible-playbook-wrapper`
variables:
  PLAYBOOK: tests/test.yml
  INVENTORY: tests/inventory

cache:
  key: "$CI_PROJECT_NAME-$CI_BUILD_NAME-cache"
  paths:
    - tests/bats-0.4.0
    - deps

centos-7:
  image: williamyeh/ansible:centos7-onbuild
  script: ./tests/ci-build
  tags:
    - ansible

alpine-3:
  image: williamyeh/ansible:alpine3-onbuild
  script: ./tests/ci-build
  only:
    - master
  tags:
    - ansible
