before_script:
  - python --version
  - ansible --version
  - mkdir tests/roles
  - ln -s $(pwd) tests/roles/diamond
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=./tests/roles' > ansible.cfg

# required for `ansible-playbook-wrapper`
variables:
  PLAYBOOK: tests/test.yml
  INVENTORY: tests/inventory

centos-7:
  image: williamyeh/ansible:centos7-onbuild
  script:
    - ansible-playbook-wrapper
    - curl -sSL -o v0.4.0.tar.gz https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz
    - tar xzf v0.4.0.tar.gz
    - ./bats-0.4.0/install.sh /usr/local
    - /usr/local/bin/bats tests/acceptance
  tags:
    - ansible
