---
- name: create diamond config directories
  file: name={{ item }} state=directory
  with_items:
    - "{{ diamond_conf_dir }}"
    - "{{ diamond_collectors_conf_dir }}"
  tags:
    - diamond
    - diamond-install

- name: install diamond dependencies
  apk: name={{ item }}
  with_items: "{{ diamond_dependencies }}"
  tags:
    - diamond
    - diamond-install

- name: install diamond
  pip: name={{ diamond_pkg_name }}
  tags:
    - diamond
    - diamond-install

- name: configure diamond service
  copy: src=init.d dest={{ diamond_service_dir }}/diamond mode=0755
  tags:
    - diamond
    - diamond-install
