---
- name: load OS specific variables
  include: "{{ item }}"
  with_first_found:
   - "install/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
   - "install/{{ ansible_distribution }}.yml"
  tags:
    - diamond
    - diamond-install

- name: load the default collectors
  template:
    src: "collectors/{{ item }}Collector.conf.j2"
    dest: "{{ diamond_collectors_conf_dir }}/{{ item }}Collector.conf"
  with_items:
    - "{{ diamond_default_collectors }}"
    - "{{ diamond_custom_collectors }}"
  notify: restart diamond
  tags:
    - diamond
    - diamond-config
    - diamond-collectors

- name: enable diamond service
  service: name=diamond enabled=yes
  tags:
    - diamond
    - diamond-service
    - diamond-install

#
# XXX: While this patch is not accepted on upstream diamond project
#
- name: Install LibvirtKVMCollector-openstack-metadata
  copy: src=libvirtkvm.py dest={{ diamond_path_collectors }}/libvirtkvm/ mode=0644 owner=root
  notify: restart diamond
  tags:
    - diamond
    - diamond-install
    - diamond-install-libvirtkvm
