---
- name: load OS specific variables
  include: "{{ item }}"
  with_first_found:
   - "install/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
   - "install/{{ ansible_distribution }}.yml"

- name: load the default collectors
  template:
    src: "collectors/{{ item }}Collector.conf.j2"
    dest: "{{ diamond_collectors_dir }}/{{ item }}Collector.conf"
  with_items:
    - "{{ diamond_default_collectors }}"
  notify: restart diamond

- name: enable diamond service
  service: name=diamond enabled=yes
  tags:
    - diamond
    - diamond-install
