---
- name: load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_distribution }}.yml"
  tags:
    - diamond
    - diamond-install

- name: diamond install tasks
  include: "install.yml"
  tags:
    - diamond
    - diamond-install

- name: deploy diamond config file
  template: src=diamond.conf.j2 dest={{ diamond_conf_dir }}/diamond.conf mode=0644 owner=root
  notify: restart diamond
  tags: diamond
