#########################################################################
# diamond role - Install and configure diamond metric collector with
#                 Multi-OS support
# ------------------------------------------------------------------
# Written By: Alexandre Biancalana - @biancalana
# ------------------------------------------------------------------
# TODO:
#########################################################################

---
- name: load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution | lower}}-{{ansible_distribution_major_version}}.yml"
   - "{{ ansible_distribution }}.yml"


- name: call install tasks
  include: install.yml

- name: deploy diamond config file
  template: src=diamond.conf.j2 dest={{ diamond_conf_dir }}/diamond.conf mode=0644 owner=root
  notify: restart diamond
  tags:
    - diamond
